version: "3.9"

services:
  networksandbox:
    image: k8s.gcr.io/pause

  # eos1100d:
  #   privileged: true
  #   image: nixery.dev/shell/ffmpeg/gphoto2
  #   profiles:
  #     - donotstart
  #   command:
  #   - sh
  #   - -c
  #   - |
  #     gphoto2 --stdout --capture-movie \
  #     | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video9

  v4l2loopback:
    privileged: true
    image: alpine
    command: modprobe v4l2loopback 
    volumes:
    - /lib/modules:/lib/modules

  alsaloopback:
    privileged: true
    image: alpine
    command: modprobe snd-aloop index=9 id=Loopback pcm_substreams=1
    volumes:
    - /lib/modules:/lib/modules

  obs:
    privileged: true
    pid: "host"
    runtime: nvidia
    network_mode: "service:networksandbox"
    ipc: host
    shm_size: '4gb'
    build:
      context: obs-studio
#      dockerfile: Dockerfile.${OBS_IMAGE_DISTRO-ubuntu}
      dockerfile: Dockerfile.from_ppa.${OBS_IMAGE_DISTRO-ubuntu}
      shm_size: '2gb'
    environment:
    - DISPLAY
    - HOME
    - USER
    - UID
    - XAUTHORITY
    - LANG
    - NVIDIA_VISIBLE_DEVICES=all
    volumes:
    - /dev:/dev
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/obs-studio:$HOME/.config/obs-studio
    - $HOME/.config/pulse:$HOME/.config/pulse
    - $HOME/.fonts/:$HOME/.fonts/
    - $XAUTHORITY:$XAUTHORITY:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - /run/user/$UID/pulse/:/var/run/pulse/
    - ./data/:/data/
    #- /usr/lib/x86_64-linux-gnu/:/local-libraries/:ro
    # Directory containing e.g. images, videos, etc. used in OBS scenes
    #- $HOME/Documents/streaming-assets:$HOME/Documents/streaming-assets
    - $HOME/Immagini/:$HOME/Immagini
    - $HOME/Scaricati/:$HOME/Scaricati/
  
    entrypoint: ["/data/start.sh"]

  streamdeck:
    privileged: true
    network_mode: "service:networksandbox"
    build: 
      context: streamdeck
      dockerfile: Dockerfile.${OBS_IMAGE_DISTRO-bullseye}
      shm_size: '2gb'
    environment:
    - DISPLAY
    - HOME
    - USER
    - UDEV=1
    - PATH=/scripts:/usr/local/bin:/usr/bin:/bin
    volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/streamdeck_ui:$HOME
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - ./bin/:/scripts/
    - ./data/:/data/
    - $HOME/recordings/:/recordings/:ro
    - $HOME/.Xauthority:/home/patane/.Xauthority:ro
    - /dev:/dev
    - /sys:/sys
    working_dir: /data
    command:
    - sh
    - -c
    - |
      chown ${UID:?please 'export UID'} $HOME
      echo $USER
      #exec su -G input -G video $USER sh -c "exec streamdeck"
      exec sh -c "/lib/systemd/systemd-udevd -d" & su -G input -G video $USER sh -c "exec streamdeck"

  countdown:
    image: python:3
    #image: new-obs-docker_streamdeck
    volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - ./bin:/usr/local/bin
    - ./data/:/data/
    working_dir: /data
    command:
    - sh
    - -c
    - |
      exec su $USER sh -c "exec countdown _"

